version: '3.8'

services:
  memory-db:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ../../data/chroma:/chroma/chroma
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/chroma

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ../../data/redis:/data
    command: redis-server --appendonly yes

  web:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.web
    ports:
      - "5000:5000"
    volumes:
      - ../../:/app
    depends_on:
      - memory-db
      - redis
    environment:
      - FLASK_ENV=development
      - MEMORY_DB_HOST=memory-db
      - REDIS_HOST=redis